# Goal
uint8 ALIGN_STRATEGY_XY_PARALLEL=1
uint8 ALIGN_STRATEGY_Y_THEN_X=2
uint8 ALIGN_STRATEGY_YAW_THEN_Y_THEN_X=3
uint8 ALIGN_STRATEGY_YAW_GATE_XY_PARALLEL=4

uint8 YAW_MODE_NONE=0
uint8 YAW_MODE_HOLD_CURRENT_ODIN_YAW=1
uint8 YAW_MODE_USE_GOAL_YAW=2

uint8 target_type
uint8 zone_id
bool use_class_id
uint8 class_id
bool use_color
uint8 color
float32 min_confidence
float32 max_frame_age_sec

float32 desired_robot_x
float32 desired_robot_y
float32 desired_robot_z
float32 tolerance_x
float32 tolerance_y
float32 tolerance_z
uint8 align_strategy
uint8 yaw_mode
float32 target_yaw_rad
float32 yaw_tolerance_rad
float32 yaw_gate_rad
uint32 timeout_ms
uint8 stable_required_frames
---
# Result
uint8 ERROR_SUCCESS=0
uint8 ERROR_NO_VISION_FRAME=1
uint8 ERROR_NO_MATCH=2
uint8 ERROR_FRAME_STALE=3
uint8 ERROR_NO_ODIN_POSE=4
uint8 ERROR_TIMEOUT=5
uint8 ERROR_CANCELED=6
uint8 ERROR_INVALID_GOAL=7

bool success
uint8 error_code
string message
float32 final_robot_x
float32 final_robot_y
float32 final_robot_z
float32 final_error_x
float32 final_error_y
float32 final_error_z
float32 final_yaw_rad
float32 final_yaw_error_rad
---
# Feedback
uint8 PHASE_WAIT_TARGET=1
uint8 PHASE_ALIGN_YAW=2
uint8 PHASE_ALIGN_Y=3
uint8 PHASE_ALIGN_X=4
uint8 PHASE_ALIGN_XY=5
uint8 PHASE_DONE=6

uint8 phase
string message
float32 current_robot_x
float32 current_robot_y
float32 current_robot_z
float32 error_x
float32 error_y
float32 error_z
float32 current_yaw_rad
float32 target_yaw_rad
float32 yaw_error_rad
float32 cmd_vx
float32 cmd_vy
float32 cmd_wz
