<?xml version="1.0"?>
<package format="3">
  <name>r2_odin_relative_move</name>
  <version>0.1.0</version>
  <description>Relative forward/lateral motion controller using Odin odometry.</description>

  <maintainer email="xie@example.com">xie</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>r2_odin_interfaces</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
