maps:
  relocalization_bin_file: /home/xie/techx_R2_algorithm/r2_algorithm/chassis_maps/test3/map_20260629_183751.bin
  relocalization_pcd_file: /home/xie/techx_R2_algorithm/r2_algorithm/chassis_maps/test3/Relocation Map4_edited.pcd
  map_package_dir: /home/xie/techx_R2_algorithm/r2_algorithm/chassis_maps/test3/Relocation Map4
ui:
  show_rviz: true
  show_map_gui: false
  launch_web: true
  launch_rosbridge: true
  launch_serial: false
  web_http_port: '8080'
frames:
  map_frame: map
  base_frame: chassis_base_link
  base_frame_candidates: chassis_base_link,odin1_base_link,base_link,base_footprint
static_tf:
  odin_to_chassis:
    x: -0.15689
    y: 0.11541
    z: -0.12233
    yaw: 0.0
    pitch: 0.0
    roll: 0.0
planner:
  robot_radius: 0.29
  max_iterations: 500000
  snap_search_radius_cells: 12
  require_ground_support: true
  strict_direct_ground_support: false
  ground_support_xy_radius_cells: 1
  ground_support_depth_cells: 1
  enable_preblocked_costmap: true
  preblocked_costmap_radius_cells: 3
  preblocked_costmap_weight: 2.5
d1_controller:
  ros__parameters:
    enable_lateral_motion: true
    tracking_target_mode: final_goal_direct
    exclusive_motion_mode: false
    translate_then_final_yaw_mode: true
    rotate_only_heading_threshold: 0.25
    max_linear_speed: 1.2
    max_lateral_speed: 1.2
    max_angular_speed: 0.7
    linear_gain: 2.2
    lateral_gain: 2.2
    heading_gain: 1.0
    cross_track_angular_gain: 0.5
    final_yaw_gain: 0.3
    goal_position_tolerance: 0.09
    goal_yaw_tolerance: 0.09
    tracking_point_reached_xy_tolerance: 0.2
    align_final_yaw: true
    linear_deadband: 0.03
    lateral_deadband: 0.03
    angular_deadband: 0.03
    enable_tracking_debug_view: false
    tracking_debug_view_size_px: 640
    tracking_debug_view_pixels_per_meter: 80.0
    tracking_debug_view_frequency: 10.0
    robot_center_offset_frame: odin1_base_link
    robot_center_offset_x: 0.0
    robot_center_offset_y: 0.0
    robot_center_offset_z: 0.0
action_server:
  ros__parameters:
    action_name: /r2_navigate_to_pose
    path_source_mode: direct_goal
    tf_wait_timeout_sec: 5.0
    path_wait_timeout_sec: 20.0
    feedback_rate_hz: 10.0
