goals:
  ENTRY_TO_B1_APPROACH:
    frame_id: map
    x: 2.054239
    y: -2.747977
    z: -0.136655
    yaw: 0.004702
  ENTRY_TO_B2_APPROACH:
    frame_id: map
    x: 2.099432
    y: -1.546507
    z: -0.145395
    yaw: -0.115381
  ENTRY_TO_B3_APPROACH:
    frame_id: map
    x: 2.171686
    y: -0.349776
    z: -0.139786
    yaw: -0.093789
  B1_TO_B2_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B2_TO_B1_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B2_TO_B3_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B3_TO_B2_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B1_TO_B4_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B4_TO_B1_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B2_TO_B5_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B5_TO_B2_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B3_TO_B6_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B6_TO_B3_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B4_TO_B5_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B5_TO_B4_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B5_TO_B6_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B6_TO_B5_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B4_TO_B7_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B7_TO_B4_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B5_TO_B8_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B8_TO_B5_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B6_TO_B9_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B9_TO_B6_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B7_TO_B8_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B8_TO_B7_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B8_TO_B9_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B9_TO_B8_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B7_TO_B10_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B10_TO_B7_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B8_TO_B11_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B11_TO_B8_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B9_TO_B12_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B12_TO_B9_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B10_TO_B11_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B11_TO_B10_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B11_TO_B12_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B12_TO_B11_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B10_TO_EXIT_ZONE_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B11_TO_EXIT_ZONE_APPROACH:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
  B12_TO_EXIT_ZONE_APPROACH:
    frame_id: map
    x: 6.982457
    y: -2.883449
    z: 0.11347
    yaw: 0.0
  GYM_HEAD_PICK_PRESET:
    frame_id: map
    x: 0.564825
    y: 0.004871
    z: -0.083427
    yaw: 0.009712
  GYM_HEAD_AFTER_PICK_ALIGN:
    frame_id: map
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
