<?xml version="1.0"?>
<package format="3">
  <name>light_signal_detector</name>
  <version>0.1.0</version>
  <description>HSV-based bright orange light signal detector for ROS 2 images.</description>

  <maintainer email="xie@example.com">xie</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>r2_light_interfaces</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>action_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
